### PR TITLE
Communication fix

### PR DESCRIPTION
**Pull request by pefribeiro**
This pull request addresses issue #7, also discussed in https://github.com/UoY-RoboStar/robochart-reference/issues/28.

### CODE REVIEW

**Comment by ana-york** [comment]
Perfect. Better than me. :-) A

**Comment by jameseb7** [comment]
You seem to have removed the review request from me. Do you still want me to review it?

**Comment by pefribeiro** [comment]
> You seem to have removed the review request from me. Do you still want me to review it?

Yes please James. Thanks.

**Review by jameseb7 — APPROVED** [review]
The change to the ecore is minor and looks fine. Checking against [RoboChart.xtext](https://github.com/UoY-RoboStar/robochart-textual/blob/master/circus.robocalc.robochart.textual/src/circus/robocalc/robochart/textual/RoboChart.xtext) confirms that it is impossible to violate the new metamodel using the textual language. It would generate blank imports if an XMI file with eventless communications were to be imported using the importer plugin, but none of the standard mutation operators we have generate such invalid mutants, so it would have to be a deliberate action on the part of a user understanding the metamodel. I'm not aware of any other plugins this could potentially break.

**Comment by pefribeiro** [comment]
Thanks @jameseb7 for your detailed analysis, that is reassuring. I also tested it locally with some existing examples, it all seemed to work fine.

**Comment by pefribeiro** [comment]
Hi Ana,

Yes you're right about this. I'll let @RandallYe know about the change. I'll also run the RoboChart/RoboSim tests after this is deployed and will check with a fresh installation of the tool to be sure.

**Comment by jameseb7** [comment]
My assumption was that RoboSim would inherit the RoboChart textual language but, looking at it, I'm uncertain what the `event` would be in the case of an [`ExecTrigger`](https://github.com/UoY-RoboStar/robosim-textual/blob/master/circus.robocalc.robosim.textual/src/circus/robocalc/robosim/textual/RoboSim.xtext#L147-L149).

**Comment by pefribeiro** [comment]
> My assumption was that RoboSim would inherit the RoboChart textual language but, looking at it, I'm uncertain what the `event` would be in the case of an [`ExecTrigger`](https://github.com/UoY-RoboStar/robosim-textual/blob/master/circus.robocalc.robosim.textual/src/circus/robocalc/robosim/textual/RoboSim.xtext#L147-L149).

It does inherit it, but I think you're right the RoboSim element `ExecTrigger` subclasses the `Communication` class modelling `exec` triggers. I'm sorry I had forgotten about this. I think in that case it will be a problem for RoboSim as the `event` attribute now cannot be null. 

I don't think there is a good way to restructure this without introducing an abstract class `Communication`, so a more pragmatic solution is to revert the change in the RoboChart metamodel, and enforce this via WFC? I'm sorry about the trouble.

**Comment by ana-york** [comment]
Pedro,

Isn't it just a case of adding a WFC to RoboSim to say that every event is
exec?  Please, don't revert it just yet.

Ana

**Comment by jameseb7** [comment]
This would also need a change to the RoboSim textual language to make `ExecTrigger`s have their `event` set to `exec`. There would also need to be a suitable `exec` event available, since `event` is a reference, rather than a contained field, so I think we can't just put in an event with the right name unless it exists somewhere else.

**Comment by ana-york** [comment]
James,

Thanks.  I had a meeting with Pedro, and he is changing the RoboSim
metamodel to include such a special event.  It already exists (I guess)
directly or indirectly, at the level of the type and scope checkers, and we
already have cycle as a special variable, with the same sort of idea.  It
should work, but Pedro is checking.

Ana

**Comment by jameseb7** [comment]
Okay, thanks for sorting that out. I agree once we have a special event it should work in the plugins, since they shouldn't need to deal directly with the event.

**Comment by pefribeiro** [comment]
Hi Ana,

@jameseb7 is quite right in that `event` is a reference, so having a special type of `Event` in the metamodel to represent `exec` does not entirely solve the problem. Instead an instance of `Event` with the name `exec` needs to be declared somewhere, ideally only once. I've looked for approaches to instantiating singleton classes in the ECore/EMF infrastructure in a systematic way but couldn't find anything illuminating.

Instead, I've adapted Alvaro's approach to declaring types, and the mathematical toolkit, in RoboChart that uses built-in libraries (ie. .rct files shipped with the plugin). I now have a built-in `robosim/score.rst` file, where there is a single interface with the event `exec`. I couldn't find a better way of just having that particular `Event` class for `exec` defined elsewhere. I'm also mindful here that the implementation of the translation to RoboSim needs to be able to find this declaration, so having it in a dedicated package/interface seems to me like a reasonable compromise, which perhaps needs some further testing.

I have then changed the scope provider for RoboSim so that in a standard `Communication` the only valid scope for an event is that `exec` declared in `score.rst`. One slight drawback is that `exec` is no longer a reserved keyword in the RoboSim grammar, but I think this a minor issue.

I've also considered removing the `OutputCommunication` class of RoboSim and re-using the RoboChart `Communication` class for Statements as well. This simplification, however, is not without issues, as it becomes impossible to distinguish '$ev' and 'ev' from the point of view of the metamodel. In the grammar we could have both options, but in either case `ev` could be any event, including that of the special `exec`, which should not be written using the dollar notation. So the rationale for having a dedicated class `OutputCommunication` still stands. I think this class may, however, be simplified by subclassing `Communication` instead.

Reflecting upon the evolution of the metamodels I now think it could have been useful to decouple references and their implementation via abstract classes. So, for example, in the case of the attribute of Communication one could could consider having an abstract notion of `Event` which could be implemented differently, either as a reference, or by another mechanism, say, a string (useful for OpenMachines), or as a special `exec` event type in the case of RoboSim.

Thanks,
Pedro

**Comment by ana-york** [comment]
Pedro,

Thanks. Let’s talk. I don’t think a library solution is the right way,
conceptually.

Ana

**Pull request merged**
